// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1981903595;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__ffi_api__open_note_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_note",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::AppError>((move || {
                let output_ok = crate::api::ffi_api::open_note(api_path)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__ffi_api__save_note_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "save_note",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_note_id = <String>::sse_decode(&mut deserializer);
            let api_expected_base_revision = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::AppError>((move || {
                let output_ok =
                    crate::api::ffi_api::save_note(api_note_id, api_expected_base_revision)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__ffi_api__search_notes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "search_notes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_query = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::error::AppError>(
                    (move || async move {
                        let output_ok = crate::api::ffi_api::search_notes(api_query).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__ffi_api__update_block_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_block",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_note_id = <String>::sse_decode(&mut deserializer);
            let api_block_path = <Vec<usize>>::sse_decode(&mut deserializer);
            let api_new_node = <crate::markdown::ast::AstNode>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::error::AppError>((move || {
                let output_ok =
                    crate::api::ffi_api::update_block(api_note_id, api_block_path, api_new_node)?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::error::AppError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::error::AppError::DiskFull;
            }
            1 => {
                return crate::error::AppError::AuthExpired;
            }
            2 => {
                return crate::error::AppError::GitConflict;
            }
            3 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::AppError::DatabaseError(var_field0);
            }
            4 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::AppError::CryptoError(var_field0);
            }
            5 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::AppError::NetworkError(var_field0);
            }
            6 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::AppError::OAuthError(var_field0);
            }
            7 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::AppError::IoError(var_field0);
            }
            8 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::error::AppError::ParseError(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::markdown::ast::AstNode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_level = <u8>::sse_decode(deserializer);
                let mut var_content =
                    <Vec<crate::markdown::ast::InlineElement>>::sse_decode(deserializer);
                return crate::markdown::ast::AstNode::Heading {
                    level: var_level,
                    content: var_content,
                };
            }
            1 => {
                let mut var_content =
                    <Vec<crate::markdown::ast::InlineElement>>::sse_decode(deserializer);
                return crate::markdown::ast::AstNode::Paragraph {
                    content: var_content,
                };
            }
            2 => {
                let mut var_ordered = <bool>::sse_decode(deserializer);
                let mut var_items = <Vec<crate::markdown::ast::AstNode>>::sse_decode(deserializer);
                return crate::markdown::ast::AstNode::List {
                    ordered: var_ordered,
                    items: var_items,
                };
            }
            3 => {
                let mut var_content =
                    <Vec<crate::markdown::ast::AstNode>>::sse_decode(deserializer);
                let mut var_checked = <Option<bool>>::sse_decode(deserializer);
                return crate::markdown::ast::AstNode::ListItem {
                    content: var_content,
                    checked: var_checked,
                };
            }
            4 => {
                let mut var_nodes = <Vec<crate::markdown::ast::AstNode>>::sse_decode(deserializer);
                return crate::markdown::ast::AstNode::Blockquote { nodes: var_nodes };
            }
            5 => {
                let mut var_language = <Option<String>>::sse_decode(deserializer);
                let mut var_code = <String>::sse_decode(deserializer);
                return crate::markdown::ast::AstNode::CodeBlock {
                    language: var_language,
                    code: var_code,
                };
            }
            6 => {
                return crate::markdown::ast::AstNode::ThematicBreak;
            }
            7 => {
                let mut var_altText = <String>::sse_decode(deserializer);
                let mut var_urlOrPath = <String>::sse_decode(deserializer);
                return crate::markdown::ast::AstNode::Image {
                    alt_text: var_altText,
                    url_or_path: var_urlOrPath,
                };
            }
            8 => {
                let mut var_baseContent =
                    <Option<Vec<crate::markdown::ast::AstNode>>>::sse_decode(deserializer);
                let mut var_localContent =
                    <Vec<crate::markdown::ast::AstNode>>::sse_decode(deserializer);
                let mut var_incomingContent =
                    <Vec<crate::markdown::ast::AstNode>>::sse_decode(deserializer);
                return crate::markdown::ast::AstNode::Suggestion {
                    base_content: var_baseContent,
                    local_content: var_localContent,
                    incoming_content: var_incomingContent,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::markdown::ast::InlineElement {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <crate::markdown::ast::TextRun>::sse_decode(deserializer);
                return crate::markdown::ast::InlineElement::Text(var_field0);
            }
            1 => {
                let mut var_targetTitle = <String>::sse_decode(deserializer);
                let mut var_resolvedNoteId = <Option<String>>::sse_decode(deserializer);
                let mut var_content =
                    <Vec<crate::markdown::ast::InlineElement>>::sse_decode(deserializer);
                return crate::markdown::ast::InlineElement::Link {
                    target_title: var_targetTitle,
                    resolved_note_id: var_resolvedNoteId,
                    content: var_content,
                };
            }
            2 => {
                let mut var_url = <String>::sse_decode(deserializer);
                let mut var_content =
                    <Vec<crate::markdown::ast::InlineElement>>::sse_decode(deserializer);
                return crate::markdown::ast::InlineElement::ExternalLink {
                    url: var_url,
                    content: var_content,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for Vec<crate::markdown::ast::AstNode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::markdown::ast::AstNode>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::markdown::ast::InlineElement> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::markdown::ast::InlineElement>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::ffi_api::NoteMetadata> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::ffi_api::NoteMetadata>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<usize> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<usize>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::ffi_api::NoteMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_workspaceId = <String>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_lastModified = <i64>::sse_decode(deserializer);
        let mut var_snippet = <Option<String>>::sse_decode(deserializer);
        return crate::api::ffi_api::NoteMetadata {
            id: var_id,
            workspace_id: var_workspaceId,
            path: var_path,
            title: var_title,
            last_modified: var_lastModified,
            snippet: var_snippet,
        };
    }
}

impl SseDecode for crate::api::ffi_api::NoteState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ast = <Vec<crate::markdown::ast::AstNode>>::sse_decode(deserializer);
        let mut var_metadata = <crate::api::ffi_api::NoteMetadata>::sse_decode(deserializer);
        let mut var_baseRevision = <String>::sse_decode(deserializer);
        return crate::api::ffi_api::NoteState {
            ast: var_ast,
            metadata: var_metadata,
            base_revision: var_baseRevision,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<bool>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<crate::markdown::ast::AstNode>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<crate::markdown::ast::AstNode>>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::markdown::ast::TextRun {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_bold = <bool>::sse_decode(deserializer);
        let mut var_italic = <bool>::sse_decode(deserializer);
        let mut var_strikethrough = <bool>::sse_decode(deserializer);
        let mut var_code = <bool>::sse_decode(deserializer);
        return crate::markdown::ast::TextRun {
            content: var_content,
            bold: var_bold,
            italic: var_italic,
            strikethrough: var_strikethrough,
            code: var_code,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__ffi_api__search_notes_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__ffi_api__open_note_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__ffi_api__save_note_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__ffi_api__update_block_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::error::AppError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::error::AppError::DiskFull => [0.into_dart()].into_dart(),
            crate::error::AppError::AuthExpired => [1.into_dart()].into_dart(),
            crate::error::AppError::GitConflict => [2.into_dart()].into_dart(),
            crate::error::AppError::DatabaseError(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AppError::CryptoError(field0) => {
                [4.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AppError::NetworkError(field0) => {
                [5.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AppError::OAuthError(field0) => {
                [6.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AppError::IoError(field0) => {
                [7.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::error::AppError::ParseError(field0) => {
                [8.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::error::AppError {}
impl flutter_rust_bridge::IntoIntoDart<crate::error::AppError> for crate::error::AppError {
    fn into_into_dart(self) -> crate::error::AppError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::markdown::ast::AstNode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::markdown::ast::AstNode::Heading { level, content } => [
                0.into_dart(),
                level.into_into_dart().into_dart(),
                content.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::markdown::ast::AstNode::Paragraph { content } => {
                [1.into_dart(), content.into_into_dart().into_dart()].into_dart()
            }
            crate::markdown::ast::AstNode::List { ordered, items } => [
                2.into_dart(),
                ordered.into_into_dart().into_dart(),
                items.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::markdown::ast::AstNode::ListItem { content, checked } => [
                3.into_dart(),
                content.into_into_dart().into_dart(),
                checked.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::markdown::ast::AstNode::Blockquote { nodes } => {
                [4.into_dart(), nodes.into_into_dart().into_dart()].into_dart()
            }
            crate::markdown::ast::AstNode::CodeBlock { language, code } => [
                5.into_dart(),
                language.into_into_dart().into_dart(),
                code.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::markdown::ast::AstNode::ThematicBreak => [6.into_dart()].into_dart(),
            crate::markdown::ast::AstNode::Image {
                alt_text,
                url_or_path,
            } => [
                7.into_dart(),
                alt_text.into_into_dart().into_dart(),
                url_or_path.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::markdown::ast::AstNode::Suggestion {
                base_content,
                local_content,
                incoming_content,
            } => [
                8.into_dart(),
                base_content.into_into_dart().into_dart(),
                local_content.into_into_dart().into_dart(),
                incoming_content.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::markdown::ast::AstNode {}
impl flutter_rust_bridge::IntoIntoDart<crate::markdown::ast::AstNode>
    for crate::markdown::ast::AstNode
{
    fn into_into_dart(self) -> crate::markdown::ast::AstNode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::markdown::ast::InlineElement {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::markdown::ast::InlineElement::Text(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::markdown::ast::InlineElement::Link {
                target_title,
                resolved_note_id,
                content,
            } => [
                1.into_dart(),
                target_title.into_into_dart().into_dart(),
                resolved_note_id.into_into_dart().into_dart(),
                content.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::markdown::ast::InlineElement::ExternalLink { url, content } => [
                2.into_dart(),
                url.into_into_dart().into_dart(),
                content.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::markdown::ast::InlineElement
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::markdown::ast::InlineElement>
    for crate::markdown::ast::InlineElement
{
    fn into_into_dart(self) -> crate::markdown::ast::InlineElement {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ffi_api::NoteMetadata {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.workspace_id.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.last_modified.into_into_dart().into_dart(),
            self.snippet.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ffi_api::NoteMetadata
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ffi_api::NoteMetadata>
    for crate::api::ffi_api::NoteMetadata
{
    fn into_into_dart(self) -> crate::api::ffi_api::NoteMetadata {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ffi_api::NoteState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ast.into_into_dart().into_dart(),
            self.metadata.into_into_dart().into_dart(),
            self.base_revision.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ffi_api::NoteState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ffi_api::NoteState>
    for crate::api::ffi_api::NoteState
{
    fn into_into_dart(self) -> crate::api::ffi_api::NoteState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::markdown::ast::TextRun {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.content.into_into_dart().into_dart(),
            self.bold.into_into_dart().into_dart(),
            self.italic.into_into_dart().into_dart(),
            self.strikethrough.into_into_dart().into_dart(),
            self.code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::markdown::ast::TextRun {}
impl flutter_rust_bridge::IntoIntoDart<crate::markdown::ast::TextRun>
    for crate::markdown::ast::TextRun
{
    fn into_into_dart(self) -> crate::markdown::ast::TextRun {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::error::AppError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::error::AppError::DiskFull => {
                <i32>::sse_encode(0, serializer);
            }
            crate::error::AppError::AuthExpired => {
                <i32>::sse_encode(1, serializer);
            }
            crate::error::AppError::GitConflict => {
                <i32>::sse_encode(2, serializer);
            }
            crate::error::AppError::DatabaseError(field0) => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::AppError::CryptoError(field0) => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::AppError::NetworkError(field0) => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::AppError::OAuthError(field0) => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::AppError::IoError(field0) => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::error::AppError::ParseError(field0) => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::markdown::ast::AstNode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::markdown::ast::AstNode::Heading { level, content } => {
                <i32>::sse_encode(0, serializer);
                <u8>::sse_encode(level, serializer);
                <Vec<crate::markdown::ast::InlineElement>>::sse_encode(content, serializer);
            }
            crate::markdown::ast::AstNode::Paragraph { content } => {
                <i32>::sse_encode(1, serializer);
                <Vec<crate::markdown::ast::InlineElement>>::sse_encode(content, serializer);
            }
            crate::markdown::ast::AstNode::List { ordered, items } => {
                <i32>::sse_encode(2, serializer);
                <bool>::sse_encode(ordered, serializer);
                <Vec<crate::markdown::ast::AstNode>>::sse_encode(items, serializer);
            }
            crate::markdown::ast::AstNode::ListItem { content, checked } => {
                <i32>::sse_encode(3, serializer);
                <Vec<crate::markdown::ast::AstNode>>::sse_encode(content, serializer);
                <Option<bool>>::sse_encode(checked, serializer);
            }
            crate::markdown::ast::AstNode::Blockquote { nodes } => {
                <i32>::sse_encode(4, serializer);
                <Vec<crate::markdown::ast::AstNode>>::sse_encode(nodes, serializer);
            }
            crate::markdown::ast::AstNode::CodeBlock { language, code } => {
                <i32>::sse_encode(5, serializer);
                <Option<String>>::sse_encode(language, serializer);
                <String>::sse_encode(code, serializer);
            }
            crate::markdown::ast::AstNode::ThematicBreak => {
                <i32>::sse_encode(6, serializer);
            }
            crate::markdown::ast::AstNode::Image {
                alt_text,
                url_or_path,
            } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(alt_text, serializer);
                <String>::sse_encode(url_or_path, serializer);
            }
            crate::markdown::ast::AstNode::Suggestion {
                base_content,
                local_content,
                incoming_content,
            } => {
                <i32>::sse_encode(8, serializer);
                <Option<Vec<crate::markdown::ast::AstNode>>>::sse_encode(base_content, serializer);
                <Vec<crate::markdown::ast::AstNode>>::sse_encode(local_content, serializer);
                <Vec<crate::markdown::ast::AstNode>>::sse_encode(incoming_content, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::markdown::ast::InlineElement {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::markdown::ast::InlineElement::Text(field0) => {
                <i32>::sse_encode(0, serializer);
                <crate::markdown::ast::TextRun>::sse_encode(field0, serializer);
            }
            crate::markdown::ast::InlineElement::Link {
                target_title,
                resolved_note_id,
                content,
            } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(target_title, serializer);
                <Option<String>>::sse_encode(resolved_note_id, serializer);
                <Vec<crate::markdown::ast::InlineElement>>::sse_encode(content, serializer);
            }
            crate::markdown::ast::InlineElement::ExternalLink { url, content } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(url, serializer);
                <Vec<crate::markdown::ast::InlineElement>>::sse_encode(content, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for Vec<crate::markdown::ast::AstNode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::markdown::ast::AstNode>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::markdown::ast::InlineElement> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::markdown::ast::InlineElement>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::ffi_api::NoteMetadata> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::ffi_api::NoteMetadata>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<usize> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <usize>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::ffi_api::NoteMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.workspace_id, serializer);
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.title, serializer);
        <i64>::sse_encode(self.last_modified, serializer);
        <Option<String>>::sse_encode(self.snippet, serializer);
    }
}

impl SseEncode for crate::api::ffi_api::NoteState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::markdown::ast::AstNode>>::sse_encode(self.ast, serializer);
        <crate::api::ffi_api::NoteMetadata>::sse_encode(self.metadata, serializer);
        <String>::sse_encode(self.base_revision, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <bool>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<crate::markdown::ast::AstNode>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<crate::markdown::ast::AstNode>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::markdown::ast::TextRun {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.content, serializer);
        <bool>::sse_encode(self.bold, serializer);
        <bool>::sse_encode(self.italic, serializer);
        <bool>::sse_encode(self.strikethrough, serializer);
        <bool>::sse_encode(self.code, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
