// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'markdown/ast.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The Core Engine's active-draft-state domain: the currently open note's
/// metadata/AST, and the in-memory cache + path-addressed mutation logic
/// `update_block` needs to apply keystroke-level edits without a disk or DB
/// round trip. Owned by this module rather than `api::ffi_api` per
/// `architecture/containers.md`'s Core Engine responsibility ("manages the
/// active draft state of open notes"), which is a distinct concern from the
/// FFI bridge — `api::ffi_api` re-exports these types and calls into this
/// module's functions, keeping its own `#[frb]` functions as thin wrappers.
class NoteMetadata {
  final String id;
  final String workspaceId;
  final String path;
  final String title;
  final PlatformInt64 lastModified;
  final String? snippet;

  const NoteMetadata({
    required this.id,
    required this.workspaceId,
    required this.path,
    required this.title,
    required this.lastModified,
    this.snippet,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      workspaceId.hashCode ^
      path.hashCode ^
      title.hashCode ^
      lastModified.hashCode ^
      snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteMetadata &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          workspaceId == other.workspaceId &&
          path == other.path &&
          title == other.title &&
          lastModified == other.lastModified &&
          snippet == other.snippet;
}

class NoteState {
  final List<AstNode> ast;
  final NoteMetadata metadata;
  final String baseRevision;

  const NoteState({
    required this.ast,
    required this.metadata,
    required this.baseRevision,
  });

  @override
  int get hashCode => ast.hashCode ^ metadata.hashCode ^ baseRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteState &&
          runtimeType == other.runtimeType &&
          ast == other.ast &&
          metadata == other.metadata &&
          baseRevision == other.baseRevision;
}
