// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class AppError with _$AppError implements FrbException {
  const AppError._();

  const factory AppError.diskFull() = AppError_DiskFull;
  const factory AppError.authExpired() = AppError_AuthExpired;
  const factory AppError.gitConflict() = AppError_GitConflict;
  const factory AppError.databaseError(String field0) = AppError_DatabaseError;
  const factory AppError.cryptoError(String field0) = AppError_CryptoError;
  const factory AppError.networkError(String field0) = AppError_NetworkError;
  const factory AppError.oAuthError(String field0) = AppError_OAuthError;
  const factory AppError.ioError(String field0) = AppError_IoError;
  const factory AppError.parseError(String field0) = AppError_ParseError;
}
