// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/ffi_api.dart';
import 'dart:async';
import 'dart:convert';
import 'draft.dart';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'index/query.dart';
import 'markdown/ast.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'workspace/bootstrap.dart';
import 'workspace/lifecycle.dart';
import 'workspace/persist.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 407307933;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAuthAuthenticateWorkspace({
    required String provider,
    required String authCode,
    required String codeVerifier,
  });

  Future<List<NoteMetadata>> crateApiFfiApiBacklinks({required String noteId});

  OAuthFlowStart crateApiAuthBeginOauthFlow({
    required String provider,
    required String redirectUri,
  });

  Future<void> crateApiFfiApiCloseNote({required String noteId});

  NoteState crateApiFfiApiCommitBlock({
    required String noteId,
    required Uint64List blockPath,
  });

  StructuralEdit crateApiFfiApiContinueBlockAfter({
    required String noteId,
    required Uint64List blockPath,
    required String source,
  });

  String crateApiFfiApiCopyRangeAsMarkdown({
    required String noteId,
    required BlockRange range,
  });

  Future<void> crateApiFfiApiCreateDirectory({required String path});

  Future<NoteState> crateApiFfiApiCreateNote({
    required String directoryPath,
    required String title,
  });

  NoteState crateApiFfiApiDeleteBlock({
    required String noteId,
    required Uint64List blockPath,
  });

  Future<List<String>> crateApiFfiApiDeleteDirectory({required String path});

  Future<void> crateApiFfiApiDeleteNote({required String noteId});

  NoteState crateApiFfiApiDeleteRange({
    required String noteId,
    required BlockRange range,
  });

  Future<List<NoteMetadata>> crateApiFfiApiFindNotesByTitle({
    required String query,
    required int limit,
  });

  Future<String> crateApiFfiApiFlushNote({required String noteId});

  String crateApiFfiApiGetBlockSource({
    required String noteId,
    required Uint64List blockPath,
  });

  Future<void> crateApiSimpleInitApp();

  NoteState crateApiFfiApiInsertBlock({
    required String noteId,
    required Uint64List blockPath,
    required String source,
  });

  Future<List<LinkCompletion>> crateApiFfiApiLinkCompletions({
    required String query,
    required int limit,
  });

  StructuralEdit crateApiFfiApiMergeBlockWithPrevious({
    required String noteId,
    required Uint64List blockPath,
  });

  Future<(NoteState, LifecycleEffects)> crateApiFfiApiMoveNote({
    required String noteId,
    required String newDirectoryPath,
  });

  NoteWriteStatus crateApiFfiApiNoteWriteStatus({required String noteId});

  Future<NoteState> crateApiFfiApiOpenNote({required String noteId});

  Future<WorkspaceInfo> crateApiFfiApiOpenOrCreateLocalWorkspace({
    String? path,
  });

  Future<WorkspaceInfo> crateApiFfiApiOpenWorkspace({required String path});

  Future<List<NoteMetadata>> crateApiFfiApiPendingDrafts();

  Future<int> crateApiFfiApiReindexWorkspace();

  Future<NoteState> crateApiFfiApiReloadNote({required String noteId});

  Future<LifecycleEffects> crateApiFfiApiRenameDirectory({
    required String path,
    required String newName,
  });

  Future<(NoteState, LifecycleEffects)> crateApiFfiApiRenameNote({
    required String noteId,
    required String newTitle,
  });

  NoteState crateApiFfiApiReplaceRange({
    required String noteId,
    required BlockRange range,
    required String replacement,
  });

  BlockCaret crateApiFfiApiResolveBlockCaret({
    required String noteId,
    required Uint64List topLevelPath,
    required BigInt renderedUtf16Offset,
  });

  Future<List<NoteMetadata>> crateApiFfiApiSearchNotes({
    required String query,
    required int limit,
  });

  StructuralEdit crateApiFfiApiSplitBlock({
    required String noteId,
    required Uint64List blockPath,
    required String source,
    required BigInt offset,
  });

  void crateApiFfiApiUpdateBlock({
    required String noteId,
    required Uint64List blockPath,
    required String newSource,
  });

  Future<List<TreeNode>> crateApiFfiApiWorkspaceTree();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAuthAuthenticateWorkspace({
    required String provider,
    required String authCode,
    required String codeVerifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          sse_encode_String(authCode, serializer);
          sse_encode_String(codeVerifier, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthAuthenticateWorkspaceConstMeta,
        argValues: [provider, authCode, codeVerifier],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthenticateWorkspaceConstMeta =>
      const TaskConstMeta(
        debugName: "authenticate_workspace",
        argNames: ["provider", "authCode", "codeVerifier"],
      );

  @override
  Future<List<NoteMetadata>> crateApiFfiApiBacklinks({required String noteId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_note_metadata,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiBacklinksConstMeta,
        argValues: [noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiBacklinksConstMeta =>
      const TaskConstMeta(debugName: "backlinks", argNames: ["noteId"]);

  @override
  OAuthFlowStart crateApiAuthBeginOauthFlow({
    required String provider,
    required String redirectUri,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          sse_encode_String(redirectUri, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_o_auth_flow_start,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthBeginOauthFlowConstMeta,
        argValues: [provider, redirectUri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthBeginOauthFlowConstMeta => const TaskConstMeta(
    debugName: "begin_oauth_flow",
    argNames: ["provider", "redirectUri"],
  );

  @override
  Future<void> crateApiFfiApiCloseNote({required String noteId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiCloseNoteConstMeta,
        argValues: [noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiCloseNoteConstMeta =>
      const TaskConstMeta(debugName: "close_note", argNames: ["noteId"]);

  @override
  NoteState crateApiFfiApiCommitBlock({
    required String noteId,
    required Uint64List blockPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_list_prim_usize_strict(blockPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_state,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiCommitBlockConstMeta,
        argValues: [noteId, blockPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiCommitBlockConstMeta => const TaskConstMeta(
    debugName: "commit_block",
    argNames: ["noteId", "blockPath"],
  );

  @override
  StructuralEdit crateApiFfiApiContinueBlockAfter({
    required String noteId,
    required Uint64List blockPath,
    required String source,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_list_prim_usize_strict(blockPath, serializer);
          sse_encode_String(source, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_structural_edit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiContinueBlockAfterConstMeta,
        argValues: [noteId, blockPath, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiContinueBlockAfterConstMeta =>
      const TaskConstMeta(
        debugName: "continue_block_after",
        argNames: ["noteId", "blockPath", "source"],
      );

  @override
  String crateApiFfiApiCopyRangeAsMarkdown({
    required String noteId,
    required BlockRange range,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_box_autoadd_block_range(range, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiCopyRangeAsMarkdownConstMeta,
        argValues: [noteId, range],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiCopyRangeAsMarkdownConstMeta =>
      const TaskConstMeta(
        debugName: "copy_range_as_markdown",
        argNames: ["noteId", "range"],
      );

  @override
  Future<void> crateApiFfiApiCreateDirectory({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiCreateDirectoryConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiCreateDirectoryConstMeta =>
      const TaskConstMeta(debugName: "create_directory", argNames: ["path"]);

  @override
  Future<NoteState> crateApiFfiApiCreateNote({
    required String directoryPath,
    required String title,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(directoryPath, serializer);
          sse_encode_String(title, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_state,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiCreateNoteConstMeta,
        argValues: [directoryPath, title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiCreateNoteConstMeta => const TaskConstMeta(
    debugName: "create_note",
    argNames: ["directoryPath", "title"],
  );

  @override
  NoteState crateApiFfiApiDeleteBlock({
    required String noteId,
    required Uint64List blockPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_list_prim_usize_strict(blockPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_state,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiDeleteBlockConstMeta,
        argValues: [noteId, blockPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiDeleteBlockConstMeta => const TaskConstMeta(
    debugName: "delete_block",
    argNames: ["noteId", "blockPath"],
  );

  @override
  Future<List<String>> crateApiFfiApiDeleteDirectory({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiDeleteDirectoryConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiDeleteDirectoryConstMeta =>
      const TaskConstMeta(debugName: "delete_directory", argNames: ["path"]);

  @override
  Future<void> crateApiFfiApiDeleteNote({required String noteId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiDeleteNoteConstMeta,
        argValues: [noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiDeleteNoteConstMeta =>
      const TaskConstMeta(debugName: "delete_note", argNames: ["noteId"]);

  @override
  NoteState crateApiFfiApiDeleteRange({
    required String noteId,
    required BlockRange range,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_box_autoadd_block_range(range, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_state,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiDeleteRangeConstMeta,
        argValues: [noteId, range],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiDeleteRangeConstMeta => const TaskConstMeta(
    debugName: "delete_range",
    argNames: ["noteId", "range"],
  );

  @override
  Future<List<NoteMetadata>> crateApiFfiApiFindNotesByTitle({
    required String query,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_note_metadata,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiFindNotesByTitleConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiFindNotesByTitleConstMeta =>
      const TaskConstMeta(
        debugName: "find_notes_by_title",
        argNames: ["query", "limit"],
      );

  @override
  Future<String> crateApiFfiApiFlushNote({required String noteId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiFlushNoteConstMeta,
        argValues: [noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiFlushNoteConstMeta =>
      const TaskConstMeta(debugName: "flush_note", argNames: ["noteId"]);

  @override
  String crateApiFfiApiGetBlockSource({
    required String noteId,
    required Uint64List blockPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_list_prim_usize_strict(blockPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiGetBlockSourceConstMeta,
        argValues: [noteId, blockPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiGetBlockSourceConstMeta =>
      const TaskConstMeta(
        debugName: "get_block_source",
        argNames: ["noteId", "blockPath"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  NoteState crateApiFfiApiInsertBlock({
    required String noteId,
    required Uint64List blockPath,
    required String source,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_list_prim_usize_strict(blockPath, serializer);
          sse_encode_String(source, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_state,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiInsertBlockConstMeta,
        argValues: [noteId, blockPath, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiInsertBlockConstMeta => const TaskConstMeta(
    debugName: "insert_block",
    argNames: ["noteId", "blockPath", "source"],
  );

  @override
  Future<List<LinkCompletion>> crateApiFfiApiLinkCompletions({
    required String query,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_link_completion,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiLinkCompletionsConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiLinkCompletionsConstMeta =>
      const TaskConstMeta(
        debugName: "link_completions",
        argNames: ["query", "limit"],
      );

  @override
  StructuralEdit crateApiFfiApiMergeBlockWithPrevious({
    required String noteId,
    required Uint64List blockPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_list_prim_usize_strict(blockPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_structural_edit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiMergeBlockWithPreviousConstMeta,
        argValues: [noteId, blockPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiMergeBlockWithPreviousConstMeta =>
      const TaskConstMeta(
        debugName: "merge_block_with_previous",
        argNames: ["noteId", "blockPath"],
      );

  @override
  Future<(NoteState, LifecycleEffects)> crateApiFfiApiMoveNote({
    required String noteId,
    required String newDirectoryPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_String(newDirectoryPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_note_state_lifecycle_effects,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiMoveNoteConstMeta,
        argValues: [noteId, newDirectoryPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiMoveNoteConstMeta => const TaskConstMeta(
    debugName: "move_note",
    argNames: ["noteId", "newDirectoryPath"],
  );

  @override
  NoteWriteStatus crateApiFfiApiNoteWriteStatus({required String noteId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_write_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFfiApiNoteWriteStatusConstMeta,
        argValues: [noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiNoteWriteStatusConstMeta =>
      const TaskConstMeta(debugName: "note_write_status", argNames: ["noteId"]);

  @override
  Future<NoteState> crateApiFfiApiOpenNote({required String noteId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_state,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiOpenNoteConstMeta,
        argValues: [noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiOpenNoteConstMeta =>
      const TaskConstMeta(debugName: "open_note", argNames: ["noteId"]);

  @override
  Future<WorkspaceInfo> crateApiFfiApiOpenOrCreateLocalWorkspace({
    String? path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_info,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiOpenOrCreateLocalWorkspaceConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiOpenOrCreateLocalWorkspaceConstMeta =>
      const TaskConstMeta(
        debugName: "open_or_create_local_workspace",
        argNames: ["path"],
      );

  @override
  Future<WorkspaceInfo> crateApiFfiApiOpenWorkspace({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_info,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiOpenWorkspaceConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiOpenWorkspaceConstMeta =>
      const TaskConstMeta(debugName: "open_workspace", argNames: ["path"]);

  @override
  Future<List<NoteMetadata>> crateApiFfiApiPendingDrafts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_note_metadata,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiPendingDraftsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiPendingDraftsConstMeta =>
      const TaskConstMeta(debugName: "pending_drafts", argNames: []);

  @override
  Future<int> crateApiFfiApiReindexWorkspace() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiReindexWorkspaceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiReindexWorkspaceConstMeta =>
      const TaskConstMeta(debugName: "reindex_workspace", argNames: []);

  @override
  Future<NoteState> crateApiFfiApiReloadNote({required String noteId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_state,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiReloadNoteConstMeta,
        argValues: [noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiReloadNoteConstMeta =>
      const TaskConstMeta(debugName: "reload_note", argNames: ["noteId"]);

  @override
  Future<LifecycleEffects> crateApiFfiApiRenameDirectory({
    required String path,
    required String newName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(newName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lifecycle_effects,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiRenameDirectoryConstMeta,
        argValues: [path, newName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiRenameDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "rename_directory",
        argNames: ["path", "newName"],
      );

  @override
  Future<(NoteState, LifecycleEffects)> crateApiFfiApiRenameNote({
    required String noteId,
    required String newTitle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_String(newTitle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_note_state_lifecycle_effects,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiRenameNoteConstMeta,
        argValues: [noteId, newTitle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiRenameNoteConstMeta => const TaskConstMeta(
    debugName: "rename_note",
    argNames: ["noteId", "newTitle"],
  );

  @override
  NoteState crateApiFfiApiReplaceRange({
    required String noteId,
    required BlockRange range,
    required String replacement,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_box_autoadd_block_range(range, serializer);
          sse_encode_String(replacement, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_state,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiReplaceRangeConstMeta,
        argValues: [noteId, range, replacement],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiReplaceRangeConstMeta => const TaskConstMeta(
    debugName: "replace_range",
    argNames: ["noteId", "range", "replacement"],
  );

  @override
  BlockCaret crateApiFfiApiResolveBlockCaret({
    required String noteId,
    required Uint64List topLevelPath,
    required BigInt renderedUtf16Offset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_list_prim_usize_strict(topLevelPath, serializer);
          sse_encode_usize(renderedUtf16Offset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_block_caret,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiResolveBlockCaretConstMeta,
        argValues: [noteId, topLevelPath, renderedUtf16Offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiResolveBlockCaretConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_block_caret",
        argNames: ["noteId", "topLevelPath", "renderedUtf16Offset"],
      );

  @override
  Future<List<NoteMetadata>> crateApiFfiApiSearchNotes({
    required String query,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_note_metadata,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiSearchNotesConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiSearchNotesConstMeta => const TaskConstMeta(
    debugName: "search_notes",
    argNames: ["query", "limit"],
  );

  @override
  StructuralEdit crateApiFfiApiSplitBlock({
    required String noteId,
    required Uint64List blockPath,
    required String source,
    required BigInt offset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_list_prim_usize_strict(blockPath, serializer);
          sse_encode_String(source, serializer);
          sse_encode_usize(offset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_structural_edit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiSplitBlockConstMeta,
        argValues: [noteId, blockPath, source, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiSplitBlockConstMeta => const TaskConstMeta(
    debugName: "split_block",
    argNames: ["noteId", "blockPath", "source", "offset"],
  );

  @override
  void crateApiFfiApiUpdateBlock({
    required String noteId,
    required Uint64List blockPath,
    required String newSource,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_list_prim_usize_strict(blockPath, serializer);
          sse_encode_String(newSource, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiUpdateBlockConstMeta,
        argValues: [noteId, blockPath, newSource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiUpdateBlockConstMeta => const TaskConstMeta(
    debugName: "update_block",
    argNames: ["noteId", "blockPath", "newSource"],
  );

  @override
  Future<List<TreeNode>> crateApiFfiApiWorkspaceTree() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tree_node,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFfiApiWorkspaceTreeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiApiWorkspaceTreeConstMeta =>
      const TaskConstMeta(debugName: "workspace_tree", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppError dco_decode_app_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AppError_DiskFull();
      case 1:
        return AppError_AuthExpired();
      case 2:
        return AppError_RevisionMismatch(dco_decode_String(raw[1]));
      case 3:
        return AppError_GitConflict();
      case 4:
        return AppError_PathUnavailable(dco_decode_String(raw[1]));
      case 5:
        return AppError_NotFound(dco_decode_String(raw[1]));
      case 6:
        return AppError_DatabaseError(dco_decode_String(raw[1]));
      case 7:
        return AppError_CryptoError(dco_decode_String(raw[1]));
      case 8:
        return AppError_NetworkError(dco_decode_String(raw[1]));
      case 9:
        return AppError_OAuthStateMismatch();
      case 10:
        return AppError_OAuthError(dco_decode_String(raw[1]));
      case 11:
        return AppError_IoError(dco_decode_String(raw[1]));
      case 12:
        return AppError_ParseError(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AstNode dco_decode_ast_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AstNode_Heading(
          level: dco_decode_u_8(raw[1]),
          content: dco_decode_list_inline_element(raw[2]),
        );
      case 1:
        return AstNode_Paragraph(
          content: dco_decode_list_inline_element(raw[1]),
        );
      case 2:
        return AstNode_List(
          ordered: dco_decode_bool(raw[1]),
          items: dco_decode_list_ast_node(raw[2]),
        );
      case 3:
        return AstNode_ListItem(
          content: dco_decode_list_ast_node(raw[1]),
          checked: dco_decode_opt_box_autoadd_bool(raw[2]),
        );
      case 4:
        return AstNode_Blockquote(nodes: dco_decode_list_ast_node(raw[1]));
      case 5:
        return AstNode_CodeBlock(
          language: dco_decode_opt_String(raw[1]),
          code: dco_decode_String(raw[2]),
        );
      case 6:
        return AstNode_ThematicBreak();
      case 7:
        return AstNode_Image(
          altText: dco_decode_String(raw[1]),
          urlOrPath: dco_decode_String(raw[2]),
        );
      case 8:
        return AstNode_Suggestion(
          baseContent: dco_decode_opt_list_ast_node(raw[1]),
          localContent: dco_decode_list_ast_node(raw[2]),
          incomingContent: dco_decode_list_ast_node(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BlockCaret dco_decode_block_caret(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BlockCaret(
      blockPath: dco_decode_list_prim_usize_strict(arr[0]),
      caretOffset: dco_decode_usize(arr[1]),
    );
  }

  @protected
  BlockRange dco_decode_block_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BlockRange(
      startPath: dco_decode_list_prim_usize_strict(arr[0]),
      startOffset: dco_decode_usize(arr[1]),
      endPath: dco_decode_list_prim_usize_strict(arr[2]),
      endOffset: dco_decode_usize(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AppError dco_decode_box_autoadd_app_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_error(raw);
  }

  @protected
  BlockRange dco_decode_box_autoadd_block_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_block_range(raw);
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  TextRun dco_decode_box_autoadd_text_run(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_text_run(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IdRemap dco_decode_id_remap(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdRemap(
      oldId: dco_decode_String(arr[0]),
      newId: dco_decode_String(arr[1]),
    );
  }

  @protected
  InlineElement dco_decode_inline_element(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return InlineElement_Text(dco_decode_box_autoadd_text_run(raw[1]));
      case 1:
        return InlineElement_Link(
          targetId: dco_decode_String(raw[1]),
          exists: dco_decode_bool(raw[2]),
          content: dco_decode_list_inline_element(raw[3]),
        );
      case 2:
        return InlineElement_ExternalLink(
          url: dco_decode_String(raw[1]),
          content: dco_decode_list_inline_element(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  LifecycleEffects dco_decode_lifecycle_effects(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LifecycleEffects(
      remapped: dco_decode_list_id_remap(arr[0]),
      rewritten: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  LinkCompletion dco_decode_link_completion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LinkCompletion(
      noteId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      insertText: dco_decode_String(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AstNode> dco_decode_list_ast_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ast_node).toList();
  }

  @protected
  List<IdRemap> dco_decode_list_id_remap(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_id_remap).toList();
  }

  @protected
  List<InlineElement> dco_decode_list_inline_element(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_inline_element).toList();
  }

  @protected
  List<LinkCompletion> dco_decode_list_link_completion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_link_completion).toList();
  }

  @protected
  List<NoteMetadata> dco_decode_list_note_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_metadata).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint64List;
  }

  @protected
  List<TreeNode> dco_decode_list_tree_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tree_node).toList();
  }

  @protected
  NoteMetadata dco_decode_note_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return NoteMetadata(
      id: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      lastModified: dco_decode_i_64(arr[3]),
      snippet: dco_decode_opt_String(arr[4]),
      okfConformant: dco_decode_bool(arr[5]),
    );
  }

  @protected
  NoteState dco_decode_note_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NoteState(
      ast: dco_decode_list_ast_node(arr[0]),
      metadata: dco_decode_note_metadata(arr[1]),
      baseRevision: dco_decode_String(arr[2]),
      restoredFromDraft: dco_decode_bool(arr[3]),
    );
  }

  @protected
  NoteWriteStatus dco_decode_note_write_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NoteWriteStatus(
      lastWrittenAt: dco_decode_opt_box_autoadd_i_64(arr[0]),
      lastError: dco_decode_opt_box_autoadd_app_error(arr[1]),
      hasUnwrittenEdits: dco_decode_bool(arr[2]),
    );
  }

  @protected
  OAuthFlowStart dco_decode_o_auth_flow_start(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OAuthFlowStart(
      authorizeUrl: dco_decode_String(arr[0]),
      codeVerifier: dco_decode_String(arr[1]),
      state: dco_decode_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AppError? dco_decode_opt_box_autoadd_app_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_app_error(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  List<AstNode>? dco_decode_opt_list_ast_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_ast_node(raw);
  }

  @protected
  (NoteState, LifecycleEffects) dco_decode_record_note_state_lifecycle_effects(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_note_state(arr[0]),
      dco_decode_lifecycle_effects(arr[1]),
    );
  }

  @protected
  StructuralEdit dco_decode_structural_edit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StructuralEdit(
      state: dco_decode_note_state(arr[0]),
      blockPath: dco_decode_list_prim_usize_strict(arr[1]),
      caretOffset: dco_decode_usize(arr[2]),
    );
  }

  @protected
  TextRun dco_decode_text_run(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TextRun(
      content: dco_decode_String(arr[0]),
      bold: dco_decode_bool(arr[1]),
      italic: dco_decode_bool(arr[2]),
      strikethrough: dco_decode_bool(arr[3]),
      code: dco_decode_bool(arr[4]),
    );
  }

  @protected
  TreeNode dco_decode_tree_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return TreeNode_Directory(
          name: dco_decode_String(raw[1]),
          path: dco_decode_String(raw[2]),
          children: dco_decode_list_tree_node(raw[3]),
        );
      case 1:
        return TreeNode_Note(
          id: dco_decode_String(raw[1]),
          title: dco_decode_String(raw[2]),
          path: dco_decode_String(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WorkspaceInfo dco_decode_workspace_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WorkspaceInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      provider: dco_decode_String(arr[2]),
      remoteUrl: dco_decode_opt_String(arr[3]),
      localPath: dco_decode_String(arr[4]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return AppError_DiskFull();
      case 1:
        return AppError_AuthExpired();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_RevisionMismatch(var_field0);
      case 3:
        return AppError_GitConflict();
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_PathUnavailable(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_NotFound(var_field0);
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_DatabaseError(var_field0);
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_CryptoError(var_field0);
      case 8:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_NetworkError(var_field0);
      case 9:
        return AppError_OAuthStateMismatch();
      case 10:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_OAuthError(var_field0);
      case 11:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_IoError(var_field0);
      case 12:
        var var_field0 = sse_decode_String(deserializer);
        return AppError_ParseError(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  AstNode sse_decode_ast_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_level = sse_decode_u_8(deserializer);
        var var_content = sse_decode_list_inline_element(deserializer);
        return AstNode_Heading(level: var_level, content: var_content);
      case 1:
        var var_content = sse_decode_list_inline_element(deserializer);
        return AstNode_Paragraph(content: var_content);
      case 2:
        var var_ordered = sse_decode_bool(deserializer);
        var var_items = sse_decode_list_ast_node(deserializer);
        return AstNode_List(ordered: var_ordered, items: var_items);
      case 3:
        var var_content = sse_decode_list_ast_node(deserializer);
        var var_checked = sse_decode_opt_box_autoadd_bool(deserializer);
        return AstNode_ListItem(content: var_content, checked: var_checked);
      case 4:
        var var_nodes = sse_decode_list_ast_node(deserializer);
        return AstNode_Blockquote(nodes: var_nodes);
      case 5:
        var var_language = sse_decode_opt_String(deserializer);
        var var_code = sse_decode_String(deserializer);
        return AstNode_CodeBlock(language: var_language, code: var_code);
      case 6:
        return AstNode_ThematicBreak();
      case 7:
        var var_altText = sse_decode_String(deserializer);
        var var_urlOrPath = sse_decode_String(deserializer);
        return AstNode_Image(altText: var_altText, urlOrPath: var_urlOrPath);
      case 8:
        var var_baseContent = sse_decode_opt_list_ast_node(deserializer);
        var var_localContent = sse_decode_list_ast_node(deserializer);
        var var_incomingContent = sse_decode_list_ast_node(deserializer);
        return AstNode_Suggestion(
          baseContent: var_baseContent,
          localContent: var_localContent,
          incomingContent: var_incomingContent,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BlockCaret sse_decode_block_caret(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_blockPath = sse_decode_list_prim_usize_strict(deserializer);
    var var_caretOffset = sse_decode_usize(deserializer);
    return BlockCaret(blockPath: var_blockPath, caretOffset: var_caretOffset);
  }

  @protected
  BlockRange sse_decode_block_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startPath = sse_decode_list_prim_usize_strict(deserializer);
    var var_startOffset = sse_decode_usize(deserializer);
    var var_endPath = sse_decode_list_prim_usize_strict(deserializer);
    var var_endOffset = sse_decode_usize(deserializer);
    return BlockRange(
      startPath: var_startPath,
      startOffset: var_startOffset,
      endPath: var_endPath,
      endOffset: var_endOffset,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AppError sse_decode_box_autoadd_app_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_error(deserializer));
  }

  @protected
  BlockRange sse_decode_box_autoadd_block_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_block_range(deserializer));
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  TextRun sse_decode_box_autoadd_text_run(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_text_run(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IdRemap sse_decode_id_remap(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_oldId = sse_decode_String(deserializer);
    var var_newId = sse_decode_String(deserializer);
    return IdRemap(oldId: var_oldId, newId: var_newId);
  }

  @protected
  InlineElement sse_decode_inline_element(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_text_run(deserializer);
        return InlineElement_Text(var_field0);
      case 1:
        var var_targetId = sse_decode_String(deserializer);
        var var_exists = sse_decode_bool(deserializer);
        var var_content = sse_decode_list_inline_element(deserializer);
        return InlineElement_Link(
          targetId: var_targetId,
          exists: var_exists,
          content: var_content,
        );
      case 2:
        var var_url = sse_decode_String(deserializer);
        var var_content = sse_decode_list_inline_element(deserializer);
        return InlineElement_ExternalLink(url: var_url, content: var_content);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  LifecycleEffects sse_decode_lifecycle_effects(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_remapped = sse_decode_list_id_remap(deserializer);
    var var_rewritten = sse_decode_list_String(deserializer);
    return LifecycleEffects(remapped: var_remapped, rewritten: var_rewritten);
  }

  @protected
  LinkCompletion sse_decode_link_completion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_noteId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_insertText = sse_decode_String(deserializer);
    return LinkCompletion(
      noteId: var_noteId,
      title: var_title,
      insertText: var_insertText,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AstNode> sse_decode_list_ast_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AstNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ast_node(deserializer));
    }
    return ans_;
  }

  @protected
  List<IdRemap> sse_decode_list_id_remap(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <IdRemap>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_id_remap(deserializer));
    }
    return ans_;
  }

  @protected
  List<InlineElement> sse_decode_list_inline_element(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InlineElement>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_inline_element(deserializer));
    }
    return ans_;
  }

  @protected
  List<LinkCompletion> sse_decode_list_link_completion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LinkCompletion>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_link_completion(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteMetadata> sse_decode_list_note_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteMetadata>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_metadata(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  List<TreeNode> sse_decode_list_tree_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TreeNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tree_node(deserializer));
    }
    return ans_;
  }

  @protected
  NoteMetadata sse_decode_note_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_lastModified = sse_decode_i_64(deserializer);
    var var_snippet = sse_decode_opt_String(deserializer);
    var var_okfConformant = sse_decode_bool(deserializer);
    return NoteMetadata(
      id: var_id,
      path: var_path,
      title: var_title,
      lastModified: var_lastModified,
      snippet: var_snippet,
      okfConformant: var_okfConformant,
    );
  }

  @protected
  NoteState sse_decode_note_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ast = sse_decode_list_ast_node(deserializer);
    var var_metadata = sse_decode_note_metadata(deserializer);
    var var_baseRevision = sse_decode_String(deserializer);
    var var_restoredFromDraft = sse_decode_bool(deserializer);
    return NoteState(
      ast: var_ast,
      metadata: var_metadata,
      baseRevision: var_baseRevision,
      restoredFromDraft: var_restoredFromDraft,
    );
  }

  @protected
  NoteWriteStatus sse_decode_note_write_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lastWrittenAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_lastError = sse_decode_opt_box_autoadd_app_error(deserializer);
    var var_hasUnwrittenEdits = sse_decode_bool(deserializer);
    return NoteWriteStatus(
      lastWrittenAt: var_lastWrittenAt,
      lastError: var_lastError,
      hasUnwrittenEdits: var_hasUnwrittenEdits,
    );
  }

  @protected
  OAuthFlowStart sse_decode_o_auth_flow_start(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_authorizeUrl = sse_decode_String(deserializer);
    var var_codeVerifier = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    return OAuthFlowStart(
      authorizeUrl: var_authorizeUrl,
      codeVerifier: var_codeVerifier,
      state: var_state,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AppError? sse_decode_opt_box_autoadd_app_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_app_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<AstNode>? sse_decode_opt_list_ast_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_ast_node(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (NoteState, LifecycleEffects) sse_decode_record_note_state_lifecycle_effects(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_note_state(deserializer);
    var var_field1 = sse_decode_lifecycle_effects(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  StructuralEdit sse_decode_structural_edit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_note_state(deserializer);
    var var_blockPath = sse_decode_list_prim_usize_strict(deserializer);
    var var_caretOffset = sse_decode_usize(deserializer);
    return StructuralEdit(
      state: var_state,
      blockPath: var_blockPath,
      caretOffset: var_caretOffset,
    );
  }

  @protected
  TextRun sse_decode_text_run(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_content = sse_decode_String(deserializer);
    var var_bold = sse_decode_bool(deserializer);
    var var_italic = sse_decode_bool(deserializer);
    var var_strikethrough = sse_decode_bool(deserializer);
    var var_code = sse_decode_bool(deserializer);
    return TextRun(
      content: var_content,
      bold: var_bold,
      italic: var_italic,
      strikethrough: var_strikethrough,
      code: var_code,
    );
  }

  @protected
  TreeNode sse_decode_tree_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_name = sse_decode_String(deserializer);
        var var_path = sse_decode_String(deserializer);
        var var_children = sse_decode_list_tree_node(deserializer);
        return TreeNode_Directory(
          name: var_name,
          path: var_path,
          children: var_children,
        );
      case 1:
        var var_id = sse_decode_String(deserializer);
        var var_title = sse_decode_String(deserializer);
        var var_path = sse_decode_String(deserializer);
        return TreeNode_Note(id: var_id, title: var_title, path: var_path);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WorkspaceInfo sse_decode_workspace_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_provider = sse_decode_String(deserializer);
    var var_remoteUrl = sse_decode_opt_String(deserializer);
    var var_localPath = sse_decode_String(deserializer);
    return WorkspaceInfo(
      id: var_id,
      name: var_name,
      provider: var_provider,
      remoteUrl: var_remoteUrl,
      localPath: var_localPath,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AppError_DiskFull():
        sse_encode_i_32(0, serializer);
      case AppError_AuthExpired():
        sse_encode_i_32(1, serializer);
      case AppError_RevisionMismatch(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case AppError_GitConflict():
        sse_encode_i_32(3, serializer);
      case AppError_PathUnavailable(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case AppError_NotFound(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case AppError_DatabaseError(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
      case AppError_CryptoError(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
      case AppError_NetworkError(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_String(field0, serializer);
      case AppError_OAuthStateMismatch():
        sse_encode_i_32(9, serializer);
      case AppError_OAuthError(field0: final field0):
        sse_encode_i_32(10, serializer);
        sse_encode_String(field0, serializer);
      case AppError_IoError(field0: final field0):
        sse_encode_i_32(11, serializer);
        sse_encode_String(field0, serializer);
      case AppError_ParseError(field0: final field0):
        sse_encode_i_32(12, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_ast_node(AstNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AstNode_Heading(level: final level, content: final content):
        sse_encode_i_32(0, serializer);
        sse_encode_u_8(level, serializer);
        sse_encode_list_inline_element(content, serializer);
      case AstNode_Paragraph(content: final content):
        sse_encode_i_32(1, serializer);
        sse_encode_list_inline_element(content, serializer);
      case AstNode_List(ordered: final ordered, items: final items):
        sse_encode_i_32(2, serializer);
        sse_encode_bool(ordered, serializer);
        sse_encode_list_ast_node(items, serializer);
      case AstNode_ListItem(content: final content, checked: final checked):
        sse_encode_i_32(3, serializer);
        sse_encode_list_ast_node(content, serializer);
        sse_encode_opt_box_autoadd_bool(checked, serializer);
      case AstNode_Blockquote(nodes: final nodes):
        sse_encode_i_32(4, serializer);
        sse_encode_list_ast_node(nodes, serializer);
      case AstNode_CodeBlock(language: final language, code: final code):
        sse_encode_i_32(5, serializer);
        sse_encode_opt_String(language, serializer);
        sse_encode_String(code, serializer);
      case AstNode_ThematicBreak():
        sse_encode_i_32(6, serializer);
      case AstNode_Image(altText: final altText, urlOrPath: final urlOrPath):
        sse_encode_i_32(7, serializer);
        sse_encode_String(altText, serializer);
        sse_encode_String(urlOrPath, serializer);
      case AstNode_Suggestion(
        baseContent: final baseContent,
        localContent: final localContent,
        incomingContent: final incomingContent,
      ):
        sse_encode_i_32(8, serializer);
        sse_encode_opt_list_ast_node(baseContent, serializer);
        sse_encode_list_ast_node(localContent, serializer);
        sse_encode_list_ast_node(incomingContent, serializer);
    }
  }

  @protected
  void sse_encode_block_caret(BlockCaret self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_usize_strict(self.blockPath, serializer);
    sse_encode_usize(self.caretOffset, serializer);
  }

  @protected
  void sse_encode_block_range(BlockRange self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_usize_strict(self.startPath, serializer);
    sse_encode_usize(self.startOffset, serializer);
    sse_encode_list_prim_usize_strict(self.endPath, serializer);
    sse_encode_usize(self.endOffset, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_app_error(
    AppError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_error(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_block_range(
    BlockRange self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_block_range(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_text_run(TextRun self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_text_run(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_id_remap(IdRemap self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.oldId, serializer);
    sse_encode_String(self.newId, serializer);
  }

  @protected
  void sse_encode_inline_element(InlineElement self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case InlineElement_Text(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_text_run(field0, serializer);
      case InlineElement_Link(
        targetId: final targetId,
        exists: final exists,
        content: final content,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(targetId, serializer);
        sse_encode_bool(exists, serializer);
        sse_encode_list_inline_element(content, serializer);
      case InlineElement_ExternalLink(url: final url, content: final content):
        sse_encode_i_32(2, serializer);
        sse_encode_String(url, serializer);
        sse_encode_list_inline_element(content, serializer);
    }
  }

  @protected
  void sse_encode_lifecycle_effects(
    LifecycleEffects self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_id_remap(self.remapped, serializer);
    sse_encode_list_String(self.rewritten, serializer);
  }

  @protected
  void sse_encode_link_completion(
    LinkCompletion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.noteId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.insertText, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ast_node(List<AstNode> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ast_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_id_remap(List<IdRemap> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_id_remap(item, serializer);
    }
  }

  @protected
  void sse_encode_list_inline_element(
    List<InlineElement> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_inline_element(item, serializer);
    }
  }

  @protected
  void sse_encode_list_link_completion(
    List<LinkCompletion> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_link_completion(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_metadata(
    List<NoteMetadata> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_metadata(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_tree_node(
    List<TreeNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tree_node(item, serializer);
    }
  }

  @protected
  void sse_encode_note_metadata(NoteMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.lastModified, serializer);
    sse_encode_opt_String(self.snippet, serializer);
    sse_encode_bool(self.okfConformant, serializer);
  }

  @protected
  void sse_encode_note_state(NoteState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_ast_node(self.ast, serializer);
    sse_encode_note_metadata(self.metadata, serializer);
    sse_encode_String(self.baseRevision, serializer);
    sse_encode_bool(self.restoredFromDraft, serializer);
  }

  @protected
  void sse_encode_note_write_status(
    NoteWriteStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.lastWrittenAt, serializer);
    sse_encode_opt_box_autoadd_app_error(self.lastError, serializer);
    sse_encode_bool(self.hasUnwrittenEdits, serializer);
  }

  @protected
  void sse_encode_o_auth_flow_start(
    OAuthFlowStart self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.authorizeUrl, serializer);
    sse_encode_String(self.codeVerifier, serializer);
    sse_encode_String(self.state, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_app_error(
    AppError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_app_error(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_ast_node(
    List<AstNode>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_ast_node(self, serializer);
    }
  }

  @protected
  void sse_encode_record_note_state_lifecycle_effects(
    (NoteState, LifecycleEffects) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_note_state(self.$1, serializer);
    sse_encode_lifecycle_effects(self.$2, serializer);
  }

  @protected
  void sse_encode_structural_edit(
    StructuralEdit self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_note_state(self.state, serializer);
    sse_encode_list_prim_usize_strict(self.blockPath, serializer);
    sse_encode_usize(self.caretOffset, serializer);
  }

  @protected
  void sse_encode_text_run(TextRun self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.content, serializer);
    sse_encode_bool(self.bold, serializer);
    sse_encode_bool(self.italic, serializer);
    sse_encode_bool(self.strikethrough, serializer);
    sse_encode_bool(self.code, serializer);
  }

  @protected
  void sse_encode_tree_node(TreeNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case TreeNode_Directory(
        name: final name,
        path: final path,
        children: final children,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(path, serializer);
        sse_encode_list_tree_node(children, serializer);
      case TreeNode_Note(id: final id, title: final title, path: final path):
        sse_encode_i_32(1, serializer);
        sse_encode_String(id, serializer);
        sse_encode_String(title, serializer);
        sse_encode_String(path, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_workspace_info(WorkspaceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.provider, serializer);
    sse_encode_opt_String(self.remoteUrl, serializer);
    sse_encode_String(self.localPath, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
