// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ffi_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'draft.dart';
import 'error.dart';
import 'frb_generated.dart';
import 'markdown/ast.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppError dco_decode_app_error(dynamic raw);

  @protected
  AstNode dco_decode_ast_node(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AstNode dco_decode_box_autoadd_ast_node(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  TextRun dco_decode_box_autoadd_text_run(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InlineElement dco_decode_inline_element(dynamic raw);

  @protected
  List<AstNode> dco_decode_list_ast_node(dynamic raw);

  @protected
  List<InlineElement> dco_decode_list_inline_element(dynamic raw);

  @protected
  List<NoteMetadata> dco_decode_list_note_metadata(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  NoteMetadata dco_decode_note_metadata(dynamic raw);

  @protected
  NoteState dco_decode_note_state(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  List<AstNode>? dco_decode_opt_list_ast_node(dynamic raw);

  @protected
  TextRun dco_decode_text_run(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer);

  @protected
  AstNode sse_decode_ast_node(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AstNode sse_decode_box_autoadd_ast_node(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  TextRun sse_decode_box_autoadd_text_run(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InlineElement sse_decode_inline_element(SseDeserializer deserializer);

  @protected
  List<AstNode> sse_decode_list_ast_node(SseDeserializer deserializer);

  @protected
  List<InlineElement> sse_decode_list_inline_element(
    SseDeserializer deserializer,
  );

  @protected
  List<NoteMetadata> sse_decode_list_note_metadata(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  NoteMetadata sse_decode_note_metadata(SseDeserializer deserializer);

  @protected
  NoteState sse_decode_note_state(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  List<AstNode>? sse_decode_opt_list_ast_node(SseDeserializer deserializer);

  @protected
  TextRun sse_decode_text_run(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer);

  @protected
  void sse_encode_ast_node(AstNode self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ast_node(AstNode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_text_run(TextRun self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_inline_element(InlineElement self, SseSerializer serializer);

  @protected
  void sse_encode_list_ast_node(List<AstNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_inline_element(
    List<InlineElement> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_metadata(
    List<NoteMetadata> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_metadata(NoteMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_note_state(NoteState self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_ast_node(
    List<AstNode>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_text_run(TextRun self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
