// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A Workspace: the bundle on disk plus its `workspaces` row
/// (`contracts/ffi_api.rs`).
class WorkspaceInfo {
  final String id;
  final String name;

  /// `"local"` until the user connects a Remote (CAP-SYNC-01), then the
  /// provider name. Matches `workspaces.provider` in `schema.sql`.
  final String provider;
  final String? remoteUrl;

  /// Absolute path to the bundle root on disk.
  final String localPath;

  const WorkspaceInfo({
    required this.id,
    required this.name,
    required this.provider,
    this.remoteUrl,
    required this.localPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      provider.hashCode ^
      remoteUrl.hashCode ^
      localPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          provider == other.provider &&
          remoteUrl == other.remoteUrl &&
          localPath == other.localPath;
}
