// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../draft.dart';
import '../frb_generated.dart';
import '../markdown/ast.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One Note whose concept id changed as a side effect of an operation on its
/// containing Directory (`contracts/ffi_api.rs`).
class IdRemap {
  final String oldId;
  final String newId;

  const IdRemap({required this.oldId, required this.newId});

  @override
  int get hashCode => oldId.hashCode ^ newId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdRemap &&
          runtimeType == other.runtimeType &&
          oldId == other.oldId &&
          newId == other.newId;
}

/// What a lifecycle operation changed, **beyond the Note it was invoked on**.
///
/// The two lists are disjoint by construction and the caller acts differently
/// on each:
///
/// - `remapped` — Notes whose **concept id** changed. An open one is holding a
///   dead identifier and must re-anchor. Empty for `rename_note` and
///   `move_note`, whose returned `NoteState` already carries the new id; it is
///   `rename_directory` that remaps Notes the caller did not name.
/// - `rewritten` — Notes whose **bytes** changed because an inbound Link in
///   them was rewritten, and whose ids did *not* change. Nothing about them
///   looks wrong, which is the problem: an open one still holds an
///   `InlineElement::Link` carrying the old `target_id`, and following it would
///   run CAP-GRAPH-04's create-on-follow into recreating the concept the rename
///   just removed.
class LifecycleEffects {
  final List<IdRemap> remapped;
  final List<String> rewritten;

  const LifecycleEffects({required this.remapped, required this.rewritten});

  @override
  int get hashCode => remapped.hashCode ^ rewritten.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LifecycleEffects &&
          runtimeType == other.runtimeType &&
          remapped == other.remapped &&
          rewritten == other.rewritten;
}

/// The authoritative outcome of any Note or Directory lifecycle operation.
///
/// FRB cannot express the operation-specific generic result shape here, so
/// all lifecycle calls use this one record. `state` is populated for create,
/// rename, and move; `effects` names reanchored and rewritten Notes;
/// `removed` names deleted Notes. A populated `warning` never reverses any of
/// those effects: Presentation must settle them first, then report it.
class LifecycleResult {
  final NoteState? state;
  final LifecycleEffects effects;
  final List<String> removed;
  final LifecycleWarning? warning;

  const LifecycleResult({
    this.state,
    required this.effects,
    required this.removed,
    this.warning,
  });

  @override
  int get hashCode =>
      state.hashCode ^ effects.hashCode ^ removed.hashCode ^ warning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LifecycleResult &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          effects == other.effects &&
          removed == other.removed &&
          warning == other.warning;
}

/// A non-fatal lifecycle warning, carried with the authoritative result.
class LifecycleWarning {
  final LifecycleWarningStage stage;
  final String detail;

  const LifecycleWarning({required this.stage, required this.detail});

  @override
  int get hashCode => stage.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LifecycleWarning &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          detail == other.detail;
}

/// The post-publication stage that completed with a recoverable warning.
///
/// This is deliberately a closed type rather than a sentence Dart must
/// inspect. A lifecycle `Err(AppError)` means neither authoritative mutation
/// nor its presentation settlement took place; a warning means the mutation
/// did take place and only its history record is missing.
enum LifecycleWarningStage { commit, settlement }
