// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One Note whose concept id changed as a side effect of an operation on its
/// containing Directory (`contracts/ffi_api.rs`).
class IdRemap {
  final String oldId;
  final String newId;

  const IdRemap({required this.oldId, required this.newId});

  @override
  int get hashCode => oldId.hashCode ^ newId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdRemap &&
          runtimeType == other.runtimeType &&
          oldId == other.oldId &&
          newId == other.newId;
}

/// What a lifecycle operation changed, **beyond the Note it was invoked on**.
///
/// The two lists are disjoint by construction and the caller acts differently
/// on each:
///
/// - `remapped` — Notes whose **concept id** changed. An open one is holding a
///   dead identifier and must re-anchor. Empty for `rename_note` and
///   `move_note`, whose returned `NoteState` already carries the new id; it is
///   `rename_directory` that remaps Notes the caller did not name.
/// - `rewritten` — Notes whose **bytes** changed because an inbound Link in
///   them was rewritten, and whose ids did *not* change. Nothing about them
///   looks wrong, which is the problem: an open one still holds an
///   `InlineElement::Link` carrying the old `target_id`, and following it would
///   run CAP-GRAPH-04's create-on-follow into recreating the concept the rename
///   just removed.
class LifecycleEffects {
  final List<IdRemap> remapped;
  final List<String> rewritten;

  const LifecycleEffects({required this.remapped, required this.rewritten});

  @override
  int get hashCode => remapped.hashCode ^ rewritten.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LifecycleEffects &&
          runtimeType == other.runtimeType &&
          remapped == other.remapped &&
          rewritten == other.rewritten;
}
