// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The state of the write tier for one open Note, polled by the UI.
///
/// A poll rather than a stream because tier 2's routine trigger is a Core-owned
/// idle timer: when its write fails there is no caller to return the error to,
/// and `RevisionMismatch` — the entirety of risk 6's mitigation — would
/// otherwise be raised into nothing.
///
/// `Default` is what a Note that is **not open** reports — no error and no
/// unwritten edits — because `note_write_status` never fails and so needs a
/// value for that case rather than an error.
class NoteWriteStatus {
  final PlatformInt64? lastWrittenAt;
  final AppError? lastError;
  final bool hasUnwrittenEdits;

  const NoteWriteStatus({
    this.lastWrittenAt,
    this.lastError,
    required this.hasUnwrittenEdits,
  });

  @override
  int get hashCode =>
      lastWrittenAt.hashCode ^ lastError.hashCode ^ hasUnwrittenEdits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteWriteStatus &&
          runtimeType == other.runtimeType &&
          lastWrittenAt == other.lastWrittenAt &&
          lastError == other.lastError &&
          hasUnwrittenEdits == other.hasUnwrittenEdits;
}
