// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The FFI shape excludes Core-selected `workspace_id` and `schema_version`.
class ActiveWorkspaceSessionSnapshot {
  final List<String> openNoteIds;
  final String? activeNoteId;
  final List<String> expandedDirectoryIds;
  final String searchQuery;
  final SessionSyncPresentation syncPresentation;

  const ActiveWorkspaceSessionSnapshot({
    required this.openNoteIds,
    this.activeNoteId,
    required this.expandedDirectoryIds,
    required this.searchQuery,
    required this.syncPresentation,
  });

  @override
  int get hashCode =>
      openNoteIds.hashCode ^
      activeNoteId.hashCode ^
      expandedDirectoryIds.hashCode ^
      searchQuery.hashCode ^
      syncPresentation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveWorkspaceSessionSnapshot &&
          runtimeType == other.runtimeType &&
          openNoteIds == other.openNoteIds &&
          activeNoteId == other.activeNoteId &&
          expandedDirectoryIds == other.expandedDirectoryIds &&
          searchQuery == other.searchQuery &&
          syncPresentation == other.syncPresentation;
}

enum SessionSyncPresentation { local, connected, paused }
