// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Presentation-only session state for the active Workspace.
///
/// Core writes the schema version and Workspace identifier into the durable
/// envelope. This FFI shape deliberately contains neither of those values.
class ActiveWorkspaceSessionSnapshot {
  /// Concept IDs of open Notes, in restore order.
  final List<String> openNoteIds;

  /// Concept ID of the active Note, if any.
  final String? activeNoteId;

  /// Expanded Directory IDs or bundle-relative paths.
  final List<String> expandedDirectoryIds;

  /// The most recent search-box text.
  final String searchQuery;

  /// Presentation-only synchronization state.
  final SessionSyncPresentation syncPresentation;

  const ActiveWorkspaceSessionSnapshot({
    required this.openNoteIds,
    this.activeNoteId,
    required this.expandedDirectoryIds,
    required this.searchQuery,
    required this.syncPresentation,
  });

  @override
  int get hashCode =>
      openNoteIds.hashCode ^
      activeNoteId.hashCode ^
      expandedDirectoryIds.hashCode ^
      searchQuery.hashCode ^
      syncPresentation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveWorkspaceSessionSnapshot &&
          runtimeType == other.runtimeType &&
          openNoteIds == other.openNoteIds &&
          activeNoteId == other.activeNoteId &&
          expandedDirectoryIds == other.expandedDirectoryIds &&
          searchQuery == other.searchQuery &&
          syncPresentation == other.syncPresentation;
}

/// Defines the saved presentation-only synchronization label.
enum SessionSyncPresentation { local, connected, paused }
