// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ast.freezed.dart';

@freezed
sealed class AstNode with _$AstNode {
  const AstNode._();

  const factory AstNode.heading({
    required int level,
    required List<InlineElement> content,
  }) = AstNode_Heading;
  const factory AstNode.paragraph({required List<InlineElement> content}) =
      AstNode_Paragraph;
  const factory AstNode.list({
    required bool ordered,
    required List<AstNode> items,
  }) = AstNode_List;
  const factory AstNode.listItem({
    required List<AstNode> content,
    bool? checked,
  }) = AstNode_ListItem;
  const factory AstNode.blockquote({required List<AstNode> nodes}) =
      AstNode_Blockquote;
  const factory AstNode.codeBlock({String? language, required String code}) =
      AstNode_CodeBlock;
  const factory AstNode.thematicBreak() = AstNode_ThematicBreak;
  const factory AstNode.image({
    required String altText,
    required String urlOrPath,
  }) = AstNode_Image;

  /// Represents a pending Git conflict that the user must resolve.
  const factory AstNode.suggestion({
    List<AstNode>? baseContent,
    required List<AstNode> localContent,
    required List<AstNode> incomingContent,
  }) = AstNode_Suggestion;
}

@freezed
sealed class InlineElement with _$InlineElement {
  const InlineElement._();

  const factory InlineElement.text(TextRun field0) = InlineElement_Text;

  /// A lateral link to another note `[[title]]`
  const factory InlineElement.link({
    required String targetTitle,
    String? resolvedNoteId,
    required List<InlineElement> content,
  }) = InlineElement_Link;

  /// A standard markdown link `[text](url)`
  const factory InlineElement.externalLink({
    required String url,
    required List<InlineElement> content,
  }) = InlineElement_ExternalLink;
}

class TextRun {
  final String content;
  final bool bold;
  final bool italic;
  final bool strikethrough;
  final bool code;

  const TextRun({
    required this.content,
    required this.bold,
    required this.italic,
    required this.strikethrough,
    required this.code,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      strikethrough.hashCode ^
      code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextRun &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          bold == other.bold &&
          italic == other.italic &&
          strikethrough == other.strikethrough &&
          code == other.code;
}
