// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ast.freezed.dart';

@freezed
sealed class AstNode with _$AstNode {
  const AstNode._();

  const factory AstNode.heading({
    required int level,
    required List<InlineElement> content,
  }) = AstNode_Heading;
  const factory AstNode.paragraph({required List<InlineElement> content}) =
      AstNode_Paragraph;
  const factory AstNode.list({
    required bool ordered,
    required List<AstNode> items,
  }) = AstNode_List;
  const factory AstNode.listItem({
    required List<AstNode> content,
    bool? checked,
  }) = AstNode_ListItem;
  const factory AstNode.blockquote({required List<AstNode> nodes}) =
      AstNode_Blockquote;
  const factory AstNode.codeBlock({String? language, required String code}) =
      AstNode_CodeBlock;
  const factory AstNode.thematicBreak() = AstNode_ThematicBreak;
  const factory AstNode.image({
    required String altText,
    required String urlOrPath,
  }) = AstNode_Image;

  /// Represents a pending Git conflict that the user must resolve.
  const factory AstNode.suggestion({
    List<AstNode>? baseContent,
    required List<AstNode> localContent,
    required List<AstNode> incomingContent,
  }) = AstNode_Suggestion;
}

@freezed
sealed class InlineElement with _$InlineElement {
  const InlineElement._();

  const factory InlineElement.text(TextRun field0) = InlineElement_Text;

  /// A Link to another Note. On disk this is a standard bundle-absolute
  /// Markdown link with an angle-bracket-wrapped destination,
  /// `[text](</dir/note.md>)` (ADR-004 decision 5, OKF §6.1) — the `[[`
  /// sequence is a UI trigger only and is never stored.
  const factory InlineElement.link({
    /// The target's OKF concept id, as `okf::links::classify` derived it
    /// from the parsed destination. Always present, even when nothing
    /// matches it.
    required String targetId,

    /// False for a ghost Link — a Link to a Note not yet created, which
    /// OKF §6.1 requires consumers to tolerate and which CAP-GRAPH-04
    /// makes a feature.
    ///
    /// Resolving this requires the index, not the parser: it is whether
    /// `target_id` matches a `notes` row. `WSPC-D003` declares the field
    /// and sits upstream of the indexer, so it leaves the field `false`
    /// and `WSPC-D005` populates it.
    ///
    /// **Advisory, and only as fresh as the state it came from.** Creating
    /// or deleting a Note flips it for every inbound Link in every other
    /// Note, so the follow path must re-resolve against the index rather
    /// than trust the flag; what it is *for* is rendering.
    required bool exists,
    required List<InlineElement> content,
  }) = InlineElement_Link;

  /// Any link that is not an internal Note reference: it has a URL scheme,
  /// or does not end in `.md`.
  const factory InlineElement.externalLink({
    required String url,
    required List<InlineElement> content,
  }) = InlineElement_ExternalLink;
}

class TextRun {
  final String content;
  final bool bold;
  final bool italic;
  final bool strikethrough;
  final bool code;

  const TextRun({
    required this.content,
    required this.bold,
    required this.italic,
    required this.strikethrough,
    required this.code,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      strikethrough.hashCode ^
      code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextRun &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          bold == other.bold &&
          italic == other.italic &&
          strikethrough == other.strikethrough &&
          code == other.code;
}
