#!/usr/bin/env bash
# Adversarial coverage for the trusted candidate launcher. This uses a tiny
# candidate source and fake Flutter/Dart commands; it never needs a device or
# touches the caller's active desktop.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd -P)
tmp=$(mktemp -d "${TMPDIR:-/tmp}/burlmd-managed-role.XXXXXXXX")
trap '[[ ${BURLMD_KEEP_FIXTURE_TMP:-} == 1 ]] || rm -rf -- "$tmp"' EXIT
mkdir -p "$tmp/source/integration_test" "$tmp/source/fixture" "$tmp/source/fixture-bin" "$tmp/parent-home" "$tmp/parent-config"
touch "$tmp/source/integration_test/fixture_test.dart"
printf '[package]\nname = "fixture"\nversion = "0.1.0"\nedition = "2024"\n' >"$tmp/source/fixture/Cargo.toml"
printf '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "fixture"\nversion = "0.1.0"\n' >"$tmp/source/fixture/Cargo.lock"
git -C "$tmp/source" init -q
git -C "$tmp/source" config user.email fixture@example.invalid
git -C "$tmp/source" config user.name fixture
git -C "$tmp/source" add .
git -C "$tmp/source" commit -qm 'fixture tested source'
printf 'parent-token-canary\n' >"$tmp/parent-home/token"
printf 'parent-config-canary\n' >"$tmp/parent-config/config"

cat >"$tmp/source/fixture-bin/flutter" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
probe="$HOME/probe"; mkdir -p "$probe"
if [[ ${1:-} == --version ]]; then printf 'fixture flutter\n'; exit 0; fi
mode=$(<../.fixture-mode)

# Inspect the actual candidate exec child without depending on a host Perl
# binary. FD 255 is Bash's CLOEXEC script reader, not an inherited capability;
# FD 10+ must not reach this child.
if [[ -d /proc ]]; then
  nonstdio_fds=()
  for fd_path in /proc/$$/fd/[0-9]*; do
    fd=${fd_path##*/}
    ((fd > 2)) && nonstdio_fds+=("$fd")
  done
  printf '%s\n' "${nonstdio_fds[@]}" >"$probe/nonstdio-fds"
fi

for name in GH_TOKEN GITHUB_TOKEN ACTIONS_RUNTIME_TOKEN ACTIONS_RUNTIME_URL ACTIONS_RESULTS_URL ACTIONS_ID_TOKEN_REQUEST_TOKEN ACTIONS_ID_TOKEN_REQUEST_URL GITHUB_ACTIONS GITHUB_ENV GITHUB_OUTPUT GITHUB_PATH GITHUB_STEP_SUMMARY GIT_ASKPASS SSH_ASKPASS SSH_AUTH_SOCK AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AZURE_CLIENT_SECRET GOOGLE_APPLICATION_CREDENTIALS; do
  [[ -z ${!name+x} ]] || { printf 'leaked:%s\n' "$name" >"$probe/leak"; exit 81; }
done
[[ $HOME == /candidate/home || $HOME == */candidate-environment/home ]] || { printf 'ambient-home\n' >"$probe/leak"; exit 82; }
candidate_root=$(dirname "$HOME")
[[ $XDG_CONFIG_HOME == "$candidate_root/xdg/config" && $GH_CONFIG_DIR == "$candidate_root/gh" && $CARGO_HOME == "$candidate_root/prepared/cargo-home" && $PUB_CACHE == "$candidate_root/prepared/pub-cache" && $CARGO_TARGET_DIR == "$candidate_root/writable/cargo-target" ]] || { printf 'owned-config-paths\n' >"$probe/leak"; exit 83; }
[[ ! -e "$HOME/token" && ! -e "$XDG_CONFIG_HOME/config" ]] || { printf 'ambient-config\n' >"$probe/leak"; exit 84; }
[[ -n ${BURLMD_CANDIDATE_SESSION:-} ]] || { printf 'missing-session\n' >"$probe/leak"; exit 85; }
case $mode in
  success)
    printf ready >"$probe/ready"
    exit 0
    ;;
  failure)
    sleep 30 & printf '%s\n' "$!" >"$probe/child.pid"
    printf ready >"$probe/ready"
    exit 41
    ;;
  detached)
    # Leave the candidate session and erase its environment. Linux Bubblewrap
    # must still reap this fresh-session descendant before returning.
    setsid env -i PATH="$PATH" HOME="$HOME" PROBE="$probe" bash -ceu 'printf "%s\n" "$$" > "$PROBE/detached.pid"; while :; do sleep 1; done' &
    for _ in $(seq 1 50); do
      if [[ -s $probe/detached.pid ]]; then
        printf ready >"$probe/ready"
        exit 0
      fi
      sleep 0.1
    done
    exit 86
    ;;
  interrupt)
    sleep 30 & printf '%s\n' "$!" >"$probe/child.pid"
    # The parent fixture only signals after this readiness marker, so it can
    # reliably assert that launcher interruption tears down the child too.
    printf ready >"$probe/ready"
    while :; do sleep 1; done
    ;;
  *) exit 87 ;;
esac
EOF
cat >"$tmp/source/fixture-bin/dart" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [[ ${1:-} == --version ]]; then printf 'fixture dart\n'; exit 0; fi
[[ $(<../.fixture-mode) == success || $(<../.fixture-mode) == detached ]] || exit 88
exit 0
EOF
cat >"$tmp/source/fixture-bin/taplo" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
pattern=${!#}
case $pattern in
  ci_bootstrap.ci_role_evidence_schema_version) printf '9\n' ;;
  'ci_bootstrap.ticket_evidence_profiles."AST-H001"."linux-x86_64"') printf '%s\n' '["common-functional"]' ;;
  reference_profiles.github-ubuntu-24_04-x86_64)
    case $(uname -m) in x86_64) observed_arch=x86_64;; arm64|aarch64) observed_arch=aarch64;; *) exit 64;; esac
    observed_cpus=$(getconf _NPROCESSORS_ONLN)
    observed_memory=$(awk '/MemTotal:/ {printf "%.0f", $2 * 1024}' /proc/meminfo)
    observed_storage=$(df -Pk . | awk 'NR==2 {printf "%.0f", $4 * 1024}')
    jq -cn --arg arch "$observed_arch" --argjson cpus "$observed_cpus" --argjson memory "$observed_memory" --argjson storage "$observed_storage" \
      '{runner_label:"ubuntu-24.04",architecture:$arch,logical_cpu_count:$cpus,memory_bytes:$memory,storage_bytes:$storage,logical_viewport_width:1920,logical_viewport_height:1080,logical_viewport_refresh_hz:60}'
    ;;
  'spikes[*]') printf '%s\n' '[{"id":"SPK-AST-H001","path":"fixture","create_commands":[{"workdir":".","command":"cargo init --bin fixture"}],"verification_steps":[{"run_role":"linux-fixture","workdir":"fixture","command":"cargo test --locked --manifest-path Cargo.toml --all-targets; flutter test ../integration_test/fixture_test.dart; mkdir -p artifacts; printf fixture > artifacts/fixture.txt; true --output artifacts/fixture.txt"}]}]' ;;
  *) printf 'unexpected taplo pattern: %s\n' "$pattern" >&2; exit 64 ;;
esac
EOF
cat >"$tmp/source/fixture-bin/check-jsonschema" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
[[ $1 == --schemafile && -f $2 && -f $3 ]]
EOF
cat >"$tmp/source/fixture-bin/cargo" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
cat >"$tmp/source/fixture-bin/cargo-expand" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
cat >"$tmp/source/fixture-bin/rustup" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
fixture_bash=$(command -v bash)
for fixture_tool in flutter dart taplo check-jsonschema cargo cargo-expand rustup; do
  sed -i "1c#!$fixture_bash" "$tmp/source/fixture-bin/$fixture_tool"
done
chmod +x "$tmp/source/fixture-bin/flutter" "$tmp/source/fixture-bin/dart" "$tmp/source/fixture-bin/taplo" "$tmp/source/fixture-bin/check-jsonschema" "$tmp/source/fixture-bin/cargo" "$tmp/source/fixture-bin/cargo-expand" "$tmp/source/fixture-bin/rustup"

assert_linux_namespace_torn_down() {
  local output=$1 lock
  lock=$(find "$output/candidate-environment" -type f -name namespace-teardown.lock -print -quit)
  [[ -n $lock ]] || { echo 'Linux candidate teardown lock was not created' >&2; return 1; }
  # The lock is held by Bubblewrap until its PID namespace reaper has exited.
  # It is therefore the host-observable no-survivor proof even though fixture
  # PIDs inside the namespace are deliberately not host PIDs.
  flock -n "$lock" true || { echo 'Linux candidate namespace survivor still holds teardown lock' >&2; return 1; }
}

run_role() {
  local mode=$1 output=$2 identity=${3:-"$tmp/expected.json"}
  printf '%s\n' "$mode" >"$tmp/source/.fixture-mode"
  # FD 10 is deliberately non-CLOEXEC. The launcher must close it before the
  # fake Flutter process starts, while preserving Bash's own script reader.
  exec 10<"$tmp/parent-home/token"
  if HOME="$tmp/parent-home" XDG_CONFIG_HOME="$tmp/parent-config" GH_TOKEN=token-canary \
    GITHUB_TOKEN=token-canary ACTIONS_RUNTIME_TOKEN=artifact-canary \
    ACTIONS_ID_TOKEN_REQUEST_TOKEN=oidc-canary SSH_AUTH_SOCK="$tmp/agent.sock" \
    AWS_SECRET_ACCESS_KEY=cloud-canary ImageOS=fixture-linux ImageVersion=fixture-image PATH="$tmp/source/fixture-bin:$PATH" \
    EXPECTED_IDENTITY="$identity" \
    "$root/scripts/run-managed-role.sh" linux-x86_64 "$tmp/source" "$output"; then
    status=0
  else
    status=$?
  fi
  exec 10<&-
  return "$status"
}

cat >"$tmp/expected.json" <<'EOF'
{"ticketIdentity":"AST-H001","releaseIdentity":"fixture","trustAnchorSha":"1111111111111111111111111111111111111111","testedSourceSha":"2222222222222222222222222222222222222222","workflowSignerSha":"3333333333333333333333333333333333333333","workflowSignerRef":"refs/heads/master","baseSha":"4444444444444444444444444444444444444444","workflowEvent":"workflow_dispatch","evidenceReportCommitPolicy":"later-reviewed-evidence-pr-with-declared-evidence-only-diff","sourceWriteAllowlist":["fixture/**"],"buildIdentity":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","corpusIdentity":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","runIdentity":"managed:0123456789abcdef0123456789abcdef","artifactNonce":"0123456789abcdef0123456789abcdef","requiredRoleIdentities":["linux-x86_64","macos-26-arm64","macos-15-arm64"],"requiredRoleSigners":{"linux-x86_64":{"workflowPath":".github/workflows/ci-role-linux-x86-64.yml","jobWorkflowRef":"SkrOYC/burlmd/.github/workflows/ci-role-linux-x86-64.yml@refs/heads/master","jobWorkflowSha":"3333333333333333333333333333333333333333"},"macos-26-arm64":{"workflowPath":".github/workflows/ci-role-macos-26-arm64.yml","jobWorkflowRef":"SkrOYC/burlmd/.github/workflows/ci-role-macos-26-arm64.yml@refs/heads/master","jobWorkflowSha":"3333333333333333333333333333333333333333"},"macos-15-arm64":{"workflowPath":".github/workflows/ci-role-macos-15-arm64.yml","jobWorkflowRef":"SkrOYC/burlmd/.github/workflows/ci-role-macos-15-arm64.yml@refs/heads/master","jobWorkflowSha":"3333333333333333333333333333333333333333"}},"requiredEvidenceClasses":{"linux-x86_64":["common-functional"],"macos-26-arm64":["common-functional"],"macos-15-arm64":["common-functional"]}}
EOF
fixture_source_sha=$(git -C "$tmp/source" rev-parse HEAD)
jq --arg source "$fixture_source_sha" '.testedSourceSha = $source' "$tmp/expected.json" >"$tmp/expected.json.next"
mv "$tmp/expected.json.next" "$tmp/expected.json"

# Any role-fixture namespace is rejected by production before it can reach a
# candidate process. Fixture host observations are supplied through the mock
# toolchain above instead of an execution-time bypass.
set +e
BURLMD_ROLE_FIXTURE_TEST_PROBE=1 EXPECTED_IDENTITY="$tmp/expected.json" \
  ImageOS=fixture-linux ImageVersion=fixture-image PATH="$tmp/source/fixture-bin:$PATH" \
  "$root/scripts/run-managed-role.sh" linux-x86_64 "$tmp/source" "$tmp/rejected-fixture-variable"
fixture_variable_status=$?
set -e
[[ $fixture_variable_status == 2 && ! -e $tmp/rejected-fixture-variable/candidate-environment ]] || {
  echo 'reserved role fixture variable was not rejected before candidate launch' >&2
  exit 1
}

# The trusted runner must reject a checkout whose actual Git commit differs
# from the authenticated testedSourceSha before discovering or launching a
# candidate command.
jq '.testedSourceSha = "0000000000000000000000000000000000000000"' "$tmp/expected.json" >"$tmp/mismatched-expected.json"
set +e
run_role success "$tmp/sha-mismatch" "$tmp/mismatched-expected.json"
sha_mismatch_status=$?
set -e
[[ $sha_mismatch_status == 2 && ! -e $tmp/sha-mismatch/candidate-environment ]] || {
  echo 'source SHA mismatch was not rejected before candidate launch' >&2
  exit 1
}

run_role success "$tmp/success"
probe="$tmp/success/candidate-environment/home/probe"
[[ -f $probe/ready && ! -e $probe/leak ]] && ! rg -qx '10' "$probe/nonstdio-fds" || {
  echo 'candidate launch leaked a descriptor, credential, or configuration canary' >&2
  exit 1
}
assert_linux_namespace_torn_down "$tmp/success"
jq -e --arg source "$fixture_source_sha" '
  .schemaVersion == 9 and .expectedIdentity.testedSourceSha == $source and
  .roleEvidence.environment.imageOS == "fixture-linux" and
  .roleEvidence.environment.imageVersion == "fixture-image" and
  (.roleEvidence.environment.osRelease | length > 0) and
  (.roleEvidence.environment.cpuModel | length > 0) and
  (.roleEvidence.environment.logicalCpuCount | type == "number" and . > 0) and
  (.roleEvidence.environment.observedMemoryBytes | type == "number" and . > 0) and
  (.roleEvidence.environment.observedStorageAvailableBytes | type == "number" and . > 0)
' "$tmp/success/ci-role-evidence.json" >/dev/null

set +e
run_role failure "$tmp/failure"
failure_status=$?
set -e
[[ $failure_status == 41 ]] || { echo "generator/test failure became $failure_status" >&2; exit 1; }
assert_linux_namespace_torn_down "$tmp/failure"

run_role detached "$tmp/detached"
[[ -s $tmp/detached/candidate-environment/home/probe/detached.pid ]] || {
  echo 'detached-process fixture did not reach the fresh session' >&2
  exit 1
}
assert_linux_namespace_torn_down "$tmp/detached"

printf 'interrupt\n' >"$tmp/source/.fixture-mode"
interrupt_output="$tmp/interrupt"
exec 10<"$tmp/parent-home/token"
HOME="$tmp/parent-home" XDG_CONFIG_HOME="$tmp/parent-config" GH_TOKEN=token-canary \
  GITHUB_TOKEN=token-canary ACTIONS_RUNTIME_TOKEN=artifact-canary \
  ACTIONS_ID_TOKEN_REQUEST_TOKEN=oidc-canary SSH_AUTH_SOCK="$tmp/agent.sock" \
  AWS_SECRET_ACCESS_KEY=cloud-canary ImageOS=fixture-linux ImageVersion=fixture-image PATH="$tmp/source/fixture-bin:$PATH" EXPECTED_IDENTITY="$tmp/expected.json" \
  "$root/scripts/run-managed-role.sh" linux-x86_64 "$tmp/source" "$interrupt_output" &
runner_pid=$!
for _ in $(seq 1 100); do
  [[ -f $interrupt_output/candidate-environment/home/probe/ready ]] && break
  kill -0 "$runner_pid" 2>/dev/null || break
  sleep 0.1
done
[[ -f $interrupt_output/candidate-environment/home/probe/ready ]] || { echo 'interruption fixture did not start candidate' >&2; exit 1; }
child_pid=$(<"$interrupt_output/candidate-environment/home/probe/child.pid")
[[ $child_pid =~ ^[1-9][0-9]*$ ]] || {
  echo 'interruption fixture candidate did not publish its namespace child PID' >&2
  exit 1
}
# Readiness and the namespace child PID are published before signalling the
# host wrapper, so cancellation cannot race candidate startup. Bubblewrap's
# die-with-parent/reaper boundary must complete before the role can return.
kill -TERM "$runner_pid"
set +e
wait "$runner_pid"
interrupt_status=$?
set -e
exec 10<&-
[[ $interrupt_status == 143 ]] || { echo "interruption returned $interrupt_status" >&2; exit 1; }
assert_linux_namespace_torn_down "$interrupt_output"

# This is the production nesting boundary, rather than a synthetic Bubblewrap
# probe: the actual trusted isolation assertion runs inside an already private
# candidate Bubblewrap namespace. Its inner sandbox receives only the exact
# locked Nix runtime closure supplied by the trusted launcher, never /nix or
# any broader host mount.
run_nested_production_isolation_fixture() {
  local tool resolved store_root bwrap_root path closure_value fixture_path missing_bwrap_value tampered_value
  local -a tools closure_paths path_entries outer_args
  tools=(bash sh env mkdir mktemp chmod awk rg bwrap cat sort readlink)
  for tool in "${tools[@]}"; do
    resolved=$(readlink -f "$(command -v "$tool")") || return 1
    [[ $resolved == /nix/store/* ]] || return 1
    store_root=$(printf '%s\n' "$resolved" | cut -d/ -f1-4)
    [[ $tool == bwrap ]] && bwrap_root=$store_root
    while IFS= read -r path; do closure_paths+=("$path"); done < <(nix-store -qR "$store_root")
    path_entries+=("$(dirname "$resolved")")
  done
  mapfile -t closure_paths < <(printf '%s\n' "${closure_paths[@]}" | LC_ALL=C sort -u)
  mapfile -t path_entries < <(printf '%s\n' "${path_entries[@]}" | LC_ALL=C sort -u)
  closure_value=$(IFS=:; printf '%s' "${closure_paths[*]}")
  fixture_path=$(IFS=:; printf '%s' "${path_entries[*]}")
  outer_args=(--unshare-all --die-with-parent --new-session --clearenv --setenv PATH "$fixture_path" --setenv BURLMD_LOCKED_NIX_CLOSURE "$closure_value" --proc /proc --dev /dev --tmpfs /tmp --dir /nix --dir /nix/store --dir /trusted --ro-bind "$root" /trusted --chdir /trusted)
  for path in "${closure_paths[@]}"; do outer_args+=(--ro-bind "$path" "$path"); done
  run_nested_assert() {
    local closure=$1 index
    local -a args=("${outer_args[@]}")
    for index in "${!args[@]}"; do
      [[ ${args[$index]} == BURLMD_LOCKED_NIX_CLOSURE ]] && args[$((index + 1))]=$closure
    done
    env -i PATH="$fixture_path" BURLMD_LOCKED_NIX_CLOSURE="$closure" \
      "$(command -v bwrap)" "${args[@]}" "$(command -v bash)" -ceu \
      'bash "$1" --contract "$2" --sandbox bubblewrap --expected-version 0.11.2' nested-isolation \
      /trusted/scripts/assert-managed-evidence-isolation.sh /trusted/.constitution/tech-spec/contracts/provisional-spikes.toml
  }
  run_nested_assert "$closure_value"

  # The nested verifier must fail closed when a trusted-launcher closure is
  # truncated or widened. These mutations happen outside the candidate mount,
  # so they exercise the actual injection boundary rather than a shell mock.
  missing_bwrap_value=$(printf '%s\n' "${closure_paths[@]}" | awk -v omitted="$bwrap_root" '$0 != omitted' | paste -sd:)
  if run_nested_assert "$missing_bwrap_value"; then
    echo 'nested isolation accepted an incomplete locked closure' >&2
    return 1
  fi
  tampered_value="$closure_value:/tmp"
  if run_nested_assert "$tampered_value"; then
    echo 'nested isolation accepted a non-store closure member' >&2
    return 1
  fi
}
run_nested_production_isolation_fixture

printf 'managed role candidate isolation fixture passed\n'
