// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `authenticate_workspace_impl`, `begin_oauth_flow_impl`, `build_authorize_url`, `current_unix_time`, `default_github_endpoints`, `exchange_code_for_token`, `fetch_github_login`, `generate_pkce`, `github_client_id`, `github_client_secret`, `new_keyring_entry`, `random_url_safe_token`, `real_endpoints`, `s256_code_challenge`, `set_or_delete`, `store_tokens_in_keyring`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GitHubOAuthEndpoints`, `OAuthTokens`, `PkceChallenge`, `RawGitHubUser`, `RawTokenError`, `RawTokenResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Starts a GitHub OAuth PKCE flow: generates the verifier/challenge/state
/// and returns the full authorize URL for the UI to open in the system
/// browser. `redirect_uri` must be the loopback URL (e.g.
/// `http://127.0.0.1:PORT/callback`) the UI is already listening on — see
/// the module doc comment on loopback redirect rules. Pure computation, no
/// network I/O, so this is `#[frb(sync)]` per `guidelines.md`'s preference
/// for synchronous FFI calls where nothing actually needs to yield.
OAuthFlowStart beginOauthFlow({
  required String provider,
  required String redirectUri,
}) => RustLib.instance.api.crateApiAuthBeginOauthFlow(
  provider: provider,
  redirectUri: redirectUri,
);

/// Exchanges `auth_code` (captured by the UI from the loopback redirect)
/// for tokens via PKCE, stores them in the OS Keychain, and returns a
/// Workspace ID. `async` per the fixed `tech-spec/contracts/ffi_api.rs`
/// signature; the body still runs synchronously to completion (blocking
/// HTTP calls, no `.await`), per `guidelines.md`'s rule that the `async`
/// marker here only affects FRB's dispatch, not this function's own
/// execution. The access/refresh tokens themselves never appear in this
/// function's `Ok` value or anywhere else that crosses the FFI boundary —
/// only the non-secret workspace id does.
Future<String> authenticateWorkspace({
  required String provider,
  required String authCode,
  required String codeVerifier,
}) => RustLib.instance.api.crateApiAuthAuthenticateWorkspace(
  provider: provider,
  authCode: authCode,
  codeVerifier: codeVerifier,
);

/// Returned by [`begin_oauth_flow`]: everything the UI needs to drive the
/// browser leg of the flow and later call `authenticate_workspace`. Beyond
/// the contract in `tech-spec/contracts/ffi_api.rs` — added here because
/// PKCE verifier/challenge/state generation, and authorize-URL construction,
/// must happen Core-side (the client secret analog here is the verifier:
/// generating it in Dart would mean trusting the UI layer with a value the
/// Core alone should mint and later check), while opening the system
/// browser and running the loopback redirect listener can only happen
/// UI-side (Rust has no notion of "the system browser" or a Flutter-visible
/// window to redirect back to).
class OAuthFlowStart {
  final String authorizeUrl;
  final String codeVerifier;
  final String state;

  const OAuthFlowStart({
    required this.authorizeUrl,
    required this.codeVerifier,
    required this.state,
  });

  @override
  int get hashCode =>
      authorizeUrl.hashCode ^ codeVerifier.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OAuthFlowStart &&
          runtimeType == other.runtimeType &&
          authorizeUrl == other.authorizeUrl &&
          codeVerifier == other.codeVerifier &&
          state == other.state;
}
