// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../draft.dart';
import '../error.dart';
import '../frb_generated.dart';
import '../markdown/ast.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fts5_phrase_query`, `save_note_impl`, `search_notes_impl`

NoteState openNote({required String path}) =>
    RustLib.instance.api.crateApiFfiApiOpenNote(path: path);

/// Applies a keystroke-level edit to the currently open note's in-memory
/// AST and returns the updated `NoteState`. `block_path` is an index path
/// into the AST tree (see `draft::set_node_at_path`); it does not persist
/// the change to disk or the DB — that happens via `save_note`.
NoteState updateBlock({
  required String noteId,
  required Uint64List blockPath,
  required AstNode newNode,
}) => RustLib.instance.api.crateApiFfiApiUpdateBlock(
  noteId: noteId,
  blockPath: blockPath,
  newNode: newNode,
);

Future<List<NoteMetadata>> searchNotes({required String query}) =>
    RustLib.instance.api.crateApiFfiApiSearchNotes(query: query);

void saveNote({required String noteId, required String expectedBaseRevision}) =>
    RustLib.instance.api.crateApiFfiApiSaveNote(
      noteId: noteId,
      expectedBaseRevision: expectedBaseRevision,
    );
