// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'query.freezed.dart';

/// One candidate for the in-editor Link completion (CAP-GRAPH-02).
class LinkCompletion {
  final String noteId;
  final String title;

  /// The exact text to splice at the cursor: a bundle-absolute Markdown
  /// link, already angle-bracket wrapped and escaped by
  /// `okf::serialize_link`. Built here, in the Core, so the UI never
  /// assembles a link target and cannot produce a non-conformant one — an
  /// ordinary multi-word title produces a path containing a space, and the
  /// unwrapped form of that is not a link at all.
  ///
  /// The link *text* is [`LinkCompletion::title`] with every whitespace run
  /// folded to a single space, so the two are not always byte-identical —
  /// see [`link_completions_impl`] for why the promise above requires it.
  final String insertText;

  const LinkCompletion({
    required this.noteId,
    required this.title,
    required this.insertText,
  });

  @override
  int get hashCode => noteId.hashCode ^ title.hashCode ^ insertText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkCompletion &&
          runtimeType == other.runtimeType &&
          noteId == other.noteId &&
          title == other.title &&
          insertText == other.insertText;
}

@freezed
sealed class TreeNode with _$TreeNode {
  const TreeNode._();

  const factory TreeNode.directory({
    required String name,
    required String path,
    required List<TreeNode> children,
  }) = TreeNode_Directory;
  const factory TreeNode.note({
    required String id,
    required String title,
    required String path,
  }) = TreeNode_Note;
}
